project:
  type: website

website:
  title: pointblank
  description: "Find out if your data is what you think it is"
  page-navigation: true
  navbar:
    left:
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/rich-iannone/pointblank

html-table-processing: none

quartodoc:
  title: API Reference
  package: pointblank
